import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import LogoutButton from "./components/LogoutButton";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";
import Image from "next/image";
import Provider from "./components/SessionProvider";





const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50`}
      >
        <Provider>
          <nav className="w-full bg-slate-900 text-white shadow-sm">
            <div className="mx-auto flex max-w-5xl items-center justify-between px-6 py-4">
              <Link href="/" className="text-xl font-semibold">
                MyAuthApp
              </Link>
              <ul className="flex items-center gap-6 text-sm">
                <li>
                  <Link href="/dashboard" className="hover:text-gray-300">
                    Dashboard
                  </Link>
                </li>
                {session?.user && (
                  <li>
                    <Link href="/profile" className="hover:text-gray-300">
                      Profile
                    </Link>
                  </li>
                )}
                {session?.user ? (
                  <li>
                    <LogoutButton />
                  </li>
                ) : (
                  <li>
                    <Link href="/api/auth/signin" className="hover:text-gray-300">
                      Sign In
                    </Link>
                  </li>
                )}
                {session?.user?.image && (
                  <li>
                    <Image
                      src={session.user.image}
                      alt={session.user.name ?? "Profile"}
                      width={40}
                      height={40}
                      className="h-10 w-10 rounded-full"
                    />
                  </li>
                )}
              </ul>
            </div>
          </nav>
          <main className="mx-auto max-w-5xl px-6 py-10">{children}</main>
        </Provider>
      </body>
    </html>
  );
}
